
type Query {
  users(id: ID, username: String): [User]! @auth
  user(id: ID!): User @auth
}

type Mutation {
  addUser(username: String!, password: String!): Boolean @auth
  changePassword(id: ID!, newPassword: String!): Boolean @auth
}

type User {
  username: String!
}