type Mutation {
  createCategory(productTypeId: ID!, name: String!): Boolean
  createSubCategory(parentId: ID!, name: String!): Boolean
  addProductToCategory(id: ID!, productId: ID!): Boolean
}

type Category {
  id: ID!
  name: String!
  parentId: ID
}

type ProductType {
  categories: [Category]!
  leafCategories: [Category]!
}

type Product {
  category: Category
}