type Query {
  productTypes(id: ID, name: String): [ProductType]!
  productType(id: ID!): ProductType
}

type Mutation {
  addProductType(name: String!, propertyNameIds: [ID]!): Boolean @auth
  deleteProductType(id: ID!): Boolean @auth

  addProductTypePropertyNames(id: ID!, propertyNameIds: [ID]!): Boolean @auth
  removeProductTypePropertyNames(id: ID!, propertyNameIds: [ID]!): Boolean @auth
}

type ProductType {
  id: ID!
  name: String!
}

type Product {
  type: ProductType!
}