
type PropertyValue {
  id: ID!
  value: String!
}

type PropertyName {
  values: [PropertyValue]
}

type Property {
  values: [PropertyValue]
}

type Stock {
  properties: [PropertyValue]
}

type AvailableProperties {
  name: String
  properties: [PropertyValue]
}