
type Mutation {
  createPropertyValue(propertyNameId: ID!, value: String!): Boolean @auth
  deletePropertyValue(id: ID!): Boolean @auth
}

type PropertyValue {
  id: ID!
  value: String!
}

type PropertyName {
  values: [PropertyValue]
}

type Property {
  values: [PropertyValue]
}

type Stock {
  properties: [PropertyValue]
}

type AvailableProperty {
  values: [PropertyValue]
}