
type Mutation {
  addPropertyValue(propertyNameId: ID!, value: String!): Boolean!
  removePropertyValue(id: ID!): Boolean!
}

type PropertyValue {
  id: ID!
  value: String!
}

type PropertyName {
  values: [PropertyValue]
}

type Property {
  values: [PropertyValue]
}

type Stock {
  properties: [PropertyValue]
}

type AvailableProperty {
  values: [PropertyValue]
}