
type FlutterwaveOrder {
  transactionRef: String!
  approveUrl: String!
}

input CustomerDetials {
  name: String!
  phonenumber: String!
  email: String!
  address: AddressInput!
}

type Mutation {
  createFlutterwaveOrder(
    returnUrl: String!,
    items: [OrderItemInput]!,
    customerDetails: CustomerDetials!
  ): FlutterwaveOrder
  verifyFlutterwaveOrder(transactionRef: String!, transactionId: String!): Boolean!
}