
type PayPalOrder {
  orderId: String!
  approveUrl: String!
}

type Mutation {
  createPayPalOrder(
    returnUrl: String!,
    cancelUrl: String,
    shippingAddress: AddressInput
    items: [OrderItemInput]!
  ): PayPalOrder
  capturePayPalOrder(orderId: String!): Boolean!
}