
type PayPalOrder {
  orderId: String!
  approveUrl: String!
}

input OrderItem {
  stockId: ID!
  quantity: Int!
}

type OrderItemDetails {
  quantity: Int!
}

type Query {
  getPayPalOrder(orderId: String!): String! @auth
  getPayPalOrderItemsDetails(orderId: String!): [OrderItemDetails]!
}

type Mutation {
  createPayPalOrder(items: [OrderItem]!, returnUrl: String, cancelUrl: String): PayPalOrder
  capturePayPalOrder(orderId: String!): Boolean!
}