
type PayPalOrder {
  orderId: String!
  approveUrl: String!
}

input OrderItem {
  stockId: ID!
  quantity: Int!
}

type Query {
  getPayPalOrder(orderId: String!): String! @auth
}

type Mutation {
  createPayPalOrder(items: [OrderItem]!): PayPalOrder #TODO: return url, cancel url
  capturePayPalOrder(orderId: String!): Boolean!
}