enum OrderStatus {
  NEW
  PROCESSED
  ARRIVED
}

enum PaymentMethod {
  PAYPAL
  FLUTTERWAVE
}

type Query {
  orders(id: ID): [Order]! @auth
  order(id: ID!): Order @auth
}

type Mutation {
  setOrderStatus(id: ID!, status: OrderStatus!): Boolean @auth
  setSupplierOrderId(id: ID!, orderId: String!): Boolean @auth
}

type Order {
  id: ID!
  paymentOrderRef: ID!
  paymentOrderId: ID
  supplierOrderId: ID
  paymentMethod: PaymentMethod!
  amountPaid: Float!
  currencyPaid: String!
  supplierCost: Float
  items: [OrderItem]!
  dateCreated: String!
  dateConfirmed: String
  status: String! 

  transactionPath: String
}

type OrderItem {
  order: Order!
}