type Query {
  products(id: ID, name: String, description: String, catagorty: String, price: Float): [Product]
  product(id: ID!): Product
}

type Product {
  id: ID!
  name: String!
  description: String
  price: Float
}