input NewProductInput {
  typeId: ID!
  name: String!
  description: String
  price: Float!
  requiredPropertyIds: [ID]!
}

input UpdatedProductInput {
  id: Int!
  name: String
  description: String
  price: Float
}

type Query {
  products(id: ID, name: String, description: String, price: Float, published: Boolean): [Product]!
  product(id: ID!): Product
}

type Mutation {
  addProduct(newProduct: NewProductInput!): Boolean @auth
  updateProduct(updatedProduct: UpdatedProductInput!): Boolean @auth
  removeProduct(id: ID!): Boolean @auth

  publishProduct(id: ID!, published: Boolean!): Boolean @auth
}

type Product {
  id: ID!
  name: String!
  description: String
  price: Float!
  published: Boolean!

  images: [String]!
  imageDir: String!
}

type ProductType {
  products: [Product]!
}

type Stock {
  product: Product!
}