
type Query {
  stockQuantity(productId: ID!, propertyValueIds: [ID]!): Int @auth
}

type Mutation {
  addStock(productId: ID!, propertyIds: [ID], quantity: Int): Boolean @auth
  updateStockQuantity(stockId: ID!, quantity: Int!): Boolean @auth
  deleteStock(id: ID!): Boolean @auth
}

type Stock {
  id: ID!
  quantity: Int @auth
  inStock: Boolean!
}

type Product {
  stock: [Stock]!
}

type OrderItem {
  stock: Stock!
}

type PropertyValue {
  stock: [Stock]!
}