type Query {
  stockQuantity(productId: ID!, propertyValueIds: [ID]!): Int
  itemInStock(productId: ID!, propertyValueIds: [ID]!): Boolean!
}

type Mutation {
  addStock(productId: ID!, propertyIds: [ID], quantity: Int): Boolean!
  updateStockQuantity(stockId: ID!, quantity: Int!): Boolean!
  deleteStock(id: ID!): Boolean!
}

type Stock {
  id: ID!
  quantity: Int!
}

type Product {
  stock: [Stock]!
}