type Query {
  stockQuantity(productId: ID!, propertyValueIds: [ID]!): Int
}

type Mutation {
  addStock(productId: ID!, propertyIds: [ID], quantity: Int): Boolean!
  updateStockQuantity(stockId: ID!, quantity: Int!): Boolean!
  deleteStock(stockId: ID!): Boolean!
}

type Stock {
  id: ID!
  quantity: Int!
}

type Product {
  stock: [Stock]!
}