type Query {
  getItemsByPayPalOrderId(orderId: String!): [OrderItem]
}

input OrderItemInput {
  stockId: ID!
  quantity: Int!
}

type OrderItem {
  id: ID!
  quantity: Int!
}

type Order {
  items: [OrderItem]!
}

type Stock {
  orders: [OrderItem]! @auth
}