type Query {
  getItemsByPayPalOrderId(orderId: String): [OrderItem]
}

type OrderItem {
  id: ID!
  quantity: Int!
}

type Order {
  items: [OrderItem]! @auth
}

type Stock {
  orders: [OrderItem]! @auth
}