scalar Upload

type Image {
  id: ID!
  path: String!
}

type Mutation {
  uploadProductImages(productId: ID!, files: [Upload]!): Boolean @auth
  deleteProductImage(imageId: ID!): Boolean @auth
}

type Product {
    images: [Image]!
}