scalar Upload

type Image {
  id: ID
  name: String
  url: String
}

type Mutation {
  uploadProductImages(productId: ID!, files: [Upload]!): Boolean
  deleteProductImage(productId: ID!, filename: String!): Boolean
}