
type Query {
  propertyNames(id: ID, name: String): [PropertyName]! @auth
  propertyName(id: ID!): PropertyName @auth
}

type Mutation {
  addPropertyName(name: String!): ID @auth
  removePropertyName(id: ID!): Boolean @auth
}

type PropertyName {
  id: ID!
  name: String!
}

type ProductType {
  propertyNames: [PropertyName]!
}

type Product {
  requiredProperties: [PropertyName]!
}

type PropertyValue {
  propertyName: PropertyName!
}