
type Query {
  propertyNames(id: ID, name: String): [PropertyName]!
  propertyName(id: ID!): PropertyName
}

type Mutation {
  addPropertyName(name: String!): Boolean
  removePropertyName(id: ID!): Boolean
}

type PropertyName {
  id: ID!
  name: String!
}

type ProductType {
  propertyNames: [PropertyName]!
}

type Product {
  requiredProperties: [PropertyName]!
}